***
Welcome! 

In this Notebook we will explore how to read external files into Python - particularly CSV and TXT files.
***

### Index:

[1.1 - Reading CSV Files](#1.1---Reading-CSV-Files)
<br>
[1.2 - Reading TXT Files](#1.2---Reading-TXT-Files)

In [1]:
# Let's load the Pandas library
import pandas as pd

# Importing the csv library
import csv

### 1.1 - Reading CSV Files

Let's first check the folders we have available on where the notebook is located:

In [4]:
!ls

01 - Reading Data from CSV and TXT Files.ipynb
02 - Scraping Data from the Web.ipynb
03 - Using API_s.ipynb
Exercises - Importing Text Data - Solutions.ipynb
Exercises - Importing Text Data.ipynb
data
exercise_data

In [6]:
import os
os.listdir()

['Exercises - Importing Text Data - Solutions.ipynb',
 '02 - Scraping Data from the Web.ipynb',
 '01 - Reading Data from CSV and TXT Files.ipynb',
 '03 - Using API_s.ipynb',
 'Exercises - Importing Text Data.ipynb',
 'data',
 'exercise_data']

In [7]:
relative_path = "./data/tweets_data.csv"
pd.read_csv(relative_path)

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [9]:
tweets_data = pd.read_csv(relative_path)
tweets_data.text

0       Our Deeds are the Reason of this #earthquake M...
1                  Forest fire near La Ronge Sask. Canada
2       All residents asked to 'shelter in place' are ...
3       13,000 people receive #wildfires evacuation or...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610    M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: str

In [10]:
tweets_data.text[2]

"All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"

In [11]:
absolute_path = "/Users/ankit/Workspace/Projects/ankit-github/AI-ML-DS/60.Natural-Language-Processing-(NLP)-in-Python/Course-Material/Natural Language Processing in Python/06 - Importing Text Data to Python/data/tweets_data.csv"
tweets_data = pd.read_csv(absolute_path)
print(tweets_data.head())

   id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...

   target
0       1
1       1
2       1
3       1
4       1

In [12]:
with open(absolute_path,mode='r',encoding='utf-8') as csv_file:
    csv_f = csv.DictReader(csv_file)
    file_data = []
    for row in csv_f:
        file_data.append(dict(row))
file_data

[{'id': '1',
  'keyword': '',
  'location': '',
  'text': 'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all',
  'target': '1'},
 {'id': '4',
  'keyword': '',
  'location': '',
  'text': 'Forest fire near La Ronge Sask. Canada',
  'target': '1'},
 {'id': '5',
  'keyword': '',
  'location': '',
  'text': "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
  'target': '1'},
 {'id': '6',
  'keyword': '',
  'location': '',
  'text': '13,000 people receive #wildfires evacuation orders in California ',
  'target': '1'},
 {'id': '7',
  'keyword': '',
  'location': '',
  'text': 'Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school ',
  'target': '1'},
 {'id': '8',
  'keyword': '',
  'location': '',
  'text': '#RockyFire Update => California Hwy. 20 closed in both directions due to Lake County fire - #CAfire #wildfires',
  'target': '1'},
 {'id': '10',
  'keyword': '',
  'location': '',
  'text': '#flood #disaster Heavy rain causes flash flooding of streets in Manitou, Colorado Springs areas',
  'target': '1'},
 {'id': '13',
  'keyword': '',
  'location': '',
  'text': "I'm on top of the hill and I can see a fire in the woods...",
  'target': '1'},
 {'id': '14',
  'keyword': '',
  'location': '',
  'text': "There's an emergency evacuation happening now in the building across the street",
  'target': '1'},
 {'id': '15',
  'keyword': '',
  'location': '',
  'text': "I'm afraid that the tornado is coming to our area...",
  'target': '1'},
 {'id': '16',
  'keyword': '',
  'location': '',
  'text': 'Three people died from the heat wave so far',
  'target': '1'},
 {'id': '17',
  'keyword': '',
  'location': '',
  'text': 'Haha South Tampa is getting flooded hah- WAIT A SECOND I LIVE IN SOUTH TAMPA WHAT AM I GONNA DO WHAT AM I GONNA DO FVCK #flooding',
  'target': '1'},
 {'id': '18',
  'keyword': '',
  'location': '',
  'text': "#raining #flooding #Florida #TampaBay #Tampa 18 or 19 days. I've lost count ",
  'target': '1'},
 {'id': '19',
  'keyword': '',
  'location': '',
  'text': '#Flood in Bago Myanmar #We arrived Bago',
  'target': '1'},
 {'id': '20',
  'keyword': '',
  'location': '',
  'text': 'Damage to school bus on 80 in multi car crash #BREAKING ',
  'target': '1'},
 {'id': '23',
  'keyword': '',
  'location': '',
  'text': "What's up man?",
  'target': '0'},
 {'id': '24',
  'keyword': '',
  'location': '',
  'text': 'I love fruits',
  'target': '0'},
 {'id': '25',
  'keyword': '',
  'location': '',
  'text': 'Summer is lovely',
  'target': '0'},
 {'id': '26',
  'keyword': '',
  'location': '',
  'text': 'My car is so fast',
  'target': '0'},
 {'id': '28',
  'keyword': '',
  'location': '',
  'text': 'What a goooooooaaaaaal!!!!!!',
  'target': '0'},
 {'id': '31',
  'keyword': '',
  'location': '',
  'text': 'this is ridiculous....',
  'target': '0'},
 {'id': '32',
  'keyword': '',
  'location': '',
  'text': 'London is cool ;)',
  'target': '0'},
 {'id': '33',
  'keyword': '',
  'location': '',
  'text': 'Love skiing',
  'target': '0'},
 {'id': '34',
  'keyword': '',
  'location': '',
  'text': 'What a wonderful day!',
  'target': '0'},
 {'id': '36',
  'keyword': '',
  'location': '',
  'text': 'LOOOOOOL',
  'target': '0'},
 {'id': '37',
  'keyword': '',
  'location': '',
  'text': "No way...I can't eat that shit",
  'target': '0'},
 {'id': '38',
  'keyword': '',
  'location': '',
  'text': 'Was in NYC last week!',
  'target': '0'},
 {'id': '39',
  'keyword': '',
  'location': '',
  'text': 'Love my girlfriend',
  'target': '0'},
 {'id': '40',
  'keyword': '',
  'location': '',
  'text': 'Cooool :)',
  'target': '0'},
 {'id': '41',
  'keyword': '',
  'location': '',
  'text': 'Do you like pasta?',
  'target': '0'},
 {'id': '44',
  'keyword': '',
  'location': '',
  'text': 'The end!',
  'target': '0'},
 {'id': '48',
  'keyword': 'ablaze',
  'location': 'Birmingham',
  'text': '@bbcmtd Wholesale Markets ablaze http://t.co/lHYXEOHY6C',
  'target': '1'},
 {'id': '49',
  'keyword': 'ablaze',
  'location': 'Est. September 2012 - Bristol',
  'text': 'We always try to bring the heavy. #metal #RT http://t.co/YAo1e0xngw',
  'target': '0'},
 {'id': '50',
  'keyword': 'ablaze',
  'location': 'AFRICA',
  'text': '#AFRICANBAZE: Breaking news:Nigeria flag set ablaze in Aba. http://t.co/2nndBGwyEi',
  'target': '1'},
 {'id': '52',
  'keyword': 'ablaze',
  'location': 'Philadelphia, PA',
  'text': 'Crying out for more! Set me ablaze',
  'target': '0'},
 {'id': '53',
  'keyword': 'ablaze',
  'location': 'London, UK',
  'text': 'On plus side LOOK AT THE SKY LAST NIGHT IT WAS ABLAZE http://t.co/qqsmshaJ3N',
  'target': '0'},
 {'id': '54',
  'keyword': 'ablaze',
  'location': 'Pretoria',
  'text': "@PhDSquares #mufc they've built so much hype around new acquisitions but I doubt they will set the EPL ablaze this season.",
  'target': '0'},
 {'id': '55',
  'keyword': 'ablaze',
  'location': 'World Wide!!',
  'text': 'INEC Office in Abia Set Ablaze - http://t.co/3ImaomknnA',
  'target': '1'},
 {'id': '56',
  'keyword': 'ablaze',
  'location': '',
  'text': 'Barbados #Bridgetown JAMAICA \x89ÛÒ Two cars set ablaze: SANTA CRUZ \x89ÛÓ Head of the St Elizabeth Police Superintende...  http://t.co/wDUEaj8Q4J',
  'target': '1'},
 {'id': '57',
  'keyword': 'ablaze',
  'location': 'Paranaque City',
  'text': 'Ablaze for you Lord :D',
  'target': '0'},
 {'id': '59',
  'keyword': 'ablaze',
  'location': 'Live On Webcam',
  'text': 'Check these out: http://t.co/rOI2NSmEJJ http://t.co/3Tj8ZjiN21 http://t.co/YDUiXEfIpE http://t.co/LxTjc87KLS #nsfw',
  'target': '0'},
 {'id': '61',
  'keyword': 'ablaze',
  'location': '',
  'text': "on the outside you're ablaze and alive\nbut you're dead inside",
  'target': '0'},
 {'id': '62',
  'keyword': 'ablaze',
  'location': 'milky way',
  'text': 'Had an awesome time visiting the CFC head office the ancop site and ablaze. Thanks to Tita Vida for taking care of us ??',
  'target': '0'},
 {'id': '63',
  'keyword': 'ablaze',
  'location': '',
  'text': 'SOOOO PUMPED FOR ABLAZE ???? @southridgelife',
  'target': '0'},
 {'id': '64',
  'keyword': 'ablaze',
  'location': '',
  'text': 'I wanted to set Chicago ablaze with my preaching... But not my hotel! http://t.co/o9qknbfOFX',
  'target': '0'},
 {'id': '65',
  'keyword': 'ablaze',
  'location': '',
  'text': 'I gained 3 followers in the last week. You? Know your stats and grow with http://t.co/TIyUliF5c6',
  'target': '0'},
 {'id': '66',
  'keyword': 'ablaze',
  'location': 'GREENSBORO,NORTH CAROLINA',
  'text': 'How the West was burned: Thousands of wildfires ablaze in California alone http://t.co/vl5TBR3wbr',
  'target': '1'},
 {'id': '67',
  'keyword': 'ablaze',
  'location': '',
  'text': 'Building the perfect tracklist to life leave the streets ablaze',
  'target': '0'},
 {'id': '68',
  'keyword': 'ablaze',
  'location': 'Live On Webcam',
  'text': 'Check these out: http://t.co/rOI2NSmEJJ http://t.co/3Tj8ZjiN21 http://t.co/YDUiXEfIpE http://t.co/LxTjc87KLS #nsfw',
  'target': '0'},
 {'id': '71',
  'keyword': 'ablaze',
  'location': 'England.',
  'text': "First night with retainers in. It's quite weird. Better get used to it; I have to wear them every single night for the next year at least.",
  'target': '0'},
 {'id': '73',
  'keyword': 'ablaze',
  'location': 'Sheffield Township, Ohio',
  'text': 'Deputies: Man shot before Brighton home set ablaze http://t.co/gWNRhMSO8k',
  'target': '1'},
 {'id': '74',
  'keyword': 'ablaze',
  'location': 'India',
  'text': 'Man wife get six years jail for setting ablaze niece\nhttp://t.co/eV1ahOUCZA',
  'target': '1'},
 {'id': '76',
  'keyword': 'ablaze',
  'location': 'Barbados',
  'text': 'SANTA CRUZ \x89ÛÓ Head of the St Elizabeth Police Superintendent Lanford Salmon has r ... - http://t.co/vplR5Hka2u http://t.co/SxHW2TNNLf',
  'target': '0'},
 {'id': '77',
  'keyword': 'ablaze',
  'location': 'Anaheim',
  'text': 'Police: Arsonist Deliberately Set Black Church In North CarolinaåÊAblaze http://t.co/pcXarbH9An',
  'target': '1'},
 {'id': '78',
  'keyword': 'ablaze',
  'location': 'Abuja',
  'text': "Noches El-Bestia '@Alexis_Sanchez: happy to see my teammates and training hard ?? goodnight gunners.?????? http://t.co/uc4j4jHvGR'",
  'target': '0'},
 {'id': '79',
  'keyword': 'ablaze',
  'location': 'USA',
  'text': '#Kurds trampling on Turkmen flag later set it ablaze while others vandalized offices of Turkmen Front in #Diyala http://t.co/4IzFdYC3cg',
  'target': '1'},
 {'id': '80',
  'keyword': 'ablaze',
  'location': 'South Africa',
  'text': 'TRUCK ABLAZE : R21. VOORTREKKER AVE. OUTSIDE OR TAMBO INTL. CARGO SECTION. http://t.co/8kscqKfKkF',
  'target': '1'},
 {'id': '81',
  'keyword': 'ablaze',
  'location': 'Sao Paulo, Brazil',
  'text': 'Set our hearts ablaze and every city was a gift And every skyline was like a kiss upon the lips @\x89Û_ https://t.co/cYoMPZ1A0Z',
  'target': '0'},
 {'id': '82',
  'keyword': 'ablaze',
  'location': 'hollywoodland ',
  'text': "They sky was ablaze tonight in Los Angeles. I'm expecting IG and FB to be filled with sunset shots if I know my peeps!!",
  'target': '0'},
 {'id': '83',
  'keyword': 'ablaze',
  'location': 'Edmonton, Alberta - Treaty 6',
  'text': 'How the West was burned: Thousands of wildfires ablaze in #California alone http://t.co/iCSjGZ9tE1 #climate #energy http://t.co/9FxmN0l0Bd',
  'target': '1'},
 {'id': '85',
  'keyword': 'ablaze',
  'location': '',
  'text': 'Revel in yours wmv videos by means of mac farewell ablaze wmv en route to dvd: GtxRWm',
  'target': '0'},
 {'id': '86',
  'keyword': 'ablaze',
  'location': 'Inang Pamantasan',
  'text': "Progressive greetings!\n\nIn about a month students would have set their pens ablaze in The Torch Publications'... http://t.co/9FxPiXQuJt",
  'target': '0'},
 {'id': '89',
  'keyword': 'ablaze',
  'location': 'Twitter Lockout in progress',
  'text': 'Rene Ablaze &amp; Jacinta - Secret 2k13 (Fallen Skies Edit) - Mar 30 2013  https://t.co/7MLMsUzV1Z',
  'target': '0'},
 {'id': '91',
  'keyword': 'ablaze',
  'location': 'Concord, CA',
  'text': "@Navista7 Steve these fires out here are something else! California is a tinderbox - and this clown was setting my 'hood ablaze @News24680",
  'target': '1'},
 {'id': '92',
  'keyword': 'ablaze',
  'location': 'Calgary, AB',
  'text': '#NowPlaying: Rene Ablaze &amp; Ian Buff - Magnitude http://t.co/Av2JSjfFtc  #EDM',
  'target': '0'},
 {'id': '93',
  'keyword': 'ablaze',
  'location': 'Birmingham',
  'text': '@nxwestmidlands huge fire at Wholesale markets ablaze http://t.co/rwzbFVNXER',
  'target': '1'},
 {'id': '95',
  'keyword': 'ablaze',
  'location': 'San Francisco',
  'text': "@ablaze what time does your talk go until? I don't know if I can make it due to work.",
  'target': '0'},
 {'id': '96',
  'keyword': 'accident',
  'location': 'CLVLND',
  'text': "'I can't have kids cuz I got in a bicycle accident &amp; split my testicles. it's impossible for me to have kids' MICHAEL YOU ARE THE FATHER",
  'target': '0'},
 {'id': '97',
  'keyword': 'accident',
  'location': 'Nashville, TN',
  'text': 'Accident on I-24 W #NashvilleTraffic. Traffic moving 8m slower than usual. https://t.co/0GHk693EgJ',
  'target': '1'},
 {'id': '98',
  'keyword': 'accident',
  'location': 'Santa Clara, CA',
  'text': 'Accident center lane blocked in #SantaClara on US-101 NB before Great America Pkwy #BayArea #Traffic http://t.co/pmlOhZuRWR',
  'target': '1'},
 {'id': '100',
  'keyword': 'accident',
  'location': 'UK',
  'text': 'http://t.co/GKYe6gjTk5 Had a #personalinjury accident this summer? Read our advice &amp; see how a #solicitor can help #OtleyHour',
  'target': '0'},
 {'id': '102',
  'keyword': 'accident',
  'location': 'St. Louis, MO',
  'text': '#stlouis #caraccidentlawyer Speeding Among Top Causes of Teen Accidents https://t.co/k4zoMOF319 https://t.co/S2kXVM0cBA Car Accident tee\x89Û_',
  'target': '0'},
 {'id': '104',
  'keyword': 'accident',
  'location': 'Walker County, Alabama',
  'text': 'Reported motor vehicle accident in Curry on Herman Rd near Stephenson involving an overturned vehicle. Please use... http://t.co/YbJezKuRW1',
  'target': '1'},
 {'id': '105',
  'keyword': 'accident',
  'location': 'Australia',
  'text': 'BigRigRadio Live Accident Awareness',
  'target': '1'},
 {'id': '107',
  'keyword': 'accident',
  'location': 'North Carolina',
  'text': 'I-77 Mile Marker 31 South Mooresville  Iredell Vehicle Accident Ramp Closed at 8/6 1:18 PM',
  'target': '1'},
 {'id': '109',
  'keyword': 'accident',
  'location': '',
  'text': 'RT @SleepJunkies: Sleeping pills double your risk of a car accident http://t.co/7s9Nm1fiCT',
  'target': '0'},
 {'id': '110',
  'keyword': 'accident',
  'location': 'Norf Carolina',
  'text': "'By accident' they knew what was gon happen https://t.co/Ysxun5vCeh",
  'target': '0'},
 {'id': '112',
  'keyword': 'accident',
  'location': 'San Mateo County, CA',
  'text': 'Traffic accident N CABRILLO HWY/MAGELLAN AV MIR (08/06/15 11:03:58)',
  'target': '1'},
 {'id': '113',
  'keyword': 'accident',
  'location': 'North Carolina',
  'text': 'I-77 Mile Marker 31 to 40 South Mooresville  Iredell Vehicle Accident Congestion at 8/6 1:18 PM',
  'target': '1'},
 {'id': '114',
  'keyword': 'accident',
  'location': 'Njoro, Kenya',
  'text': 'the pastor was not in the scene of the accident......who was the owner of the range rover ?',
  'target': '1'},
 {'id': '117',
  'keyword': 'accident',
  'location': '',
  'text': "mom: 'we didn't get home as fast as we wished' \nme: 'why is that?'\nmom: 'there was an accident and some truck spilt mayonnaise all over ??????",
  'target': '0'},
 {'id': '118',
  'keyword': 'accident',
  'location': "Your Sister's Bedroom",
  'text': "I was in a horrible car accident this past Sunday. I'm finally able to get around. Thank you GOD??",
  'target': '1'},
 {'id': '119',
  'keyword': 'accident',
  'location': '',
  'text': 'Can wait to see how pissed Donnie is when I tell him I was in ANOTHER accident??',
  'target': '0'},
 {'id': '120',
  'keyword': 'accident',
  'location': 'Arlington, TX',
  'text': "#TruckCrash Overturns On #FortWorth Interstate http://t.co/Rs22LJ4qFp Click here if you've been in a crash&gt;http://t.co/Ld0unIYw4k",
  'target': '1'},
 {'id': '121',
  'keyword': 'accident',
  'location': 'South Bloomfield, OH',
  'text': 'Accident in #Ashville on US 23 SB before SR 752 #traffic http://t.co/hylMo0WgFI',
  'target': '1'},
 {'id': '126',
  'keyword': 'accident',
  'location': '',
  'text': 'Carolina accident: Motorcyclist Dies in I-540 Crash With Car That Crossed Median: A motorcycle rider traveling... http://t.co/p18lzRlmy6',
  'target': '1'},
 {'id': '128',
  'keyword': 'accident',
  'location': 'New Hanover County, NC',
  'text': 'FYI CAD:FYI: ;ACCIDENT PROPERTY DAMAGE;NHS;999 PINER RD/HORNDALE DR',
  'target': '1'},
 {'id': '129',
  'keyword': 'accident',
  'location': 'Maldives',
  'text': 'RT nAAYf: First accident in years. Turning onto Chandanee Magu from near MMA. Taxi rammed into me while I was halfway turned. Everyone conf\x89Û_',
  'target': '1'},
 {'id': '130',
  'keyword': 'accident',
  'location': 'Manchester, NH',
  'text': 'Accident left lane blocked in #Manchester on Rt 293 NB before Eddy Rd stop and go traffic back to NH-3A delay of 4 mins #traffic',
  'target': '1'},
 {'id': '131',
  'keyword': 'accident',
  'location': 'Wilmington, NC',
  'text': ';ACCIDENT PROPERTY DAMAGE; PINER RD/HORNDALE DR',
  'target': '1'},
 {'id': '132',
  'keyword': 'accident',
  'location': '',
  'text': '???? it was an accident http://t.co/Oia5fxi4gM',
  'target': '0'},
 {'id': '133',
  'keyword': 'accident',
  'location': 'New Hanover County, NC',
  'text': 'FYI CAD:FYI: ;ACCIDENT PROPERTY DAMAGE;WPD;1600 S 17TH ST',
  'target': '1'},
 {'id': '134',
  'keyword': 'accident',
  'location': '',
  'text': '8/6/2015@2:09 PM: TRAFFIC ACCIDENT NO INJURY at 2781 WILLIS FOREMAN RD http://t.co/VCkIT6EDEv',
  'target': '1'},
 {'id': '135',
  'keyword': 'accident',
  'location': 'global',
  'text': 'Aashiqui Actress Anu Aggarwal On Her Near-Fatal Accident http://t.co/6Otfp31LqW',
  'target': '1'},
 {'id': '136',
  'keyword': 'accident',
  'location': 'Alberta | Sask. | Montana',
  'text': 'Suffield Alberta Accident https://t.co/bPTmlF4P10',
  'target': '1'},
 {'id': '137',
  'keyword': 'accident',
  'location': 'Charlotte',
  'text': '9 Mile backup on I-77 South...accident blocking the Right 2 Lanes at Exit 31 Langtree Rd...consider NC 115 or NC 150 to NC 16 as alternate',
  'target': '1'},
 {'id': '138',
  'keyword': 'accident',
  'location': 'Baton Rouge, LA',
  'text': 'Has an accident changed your life? We will help you determine options that can financially support life care plans and on-going treatment.',
  'target': '0'},
 {'id': '139',
  'keyword': 'accident',
  'location': 'Hagerstown, MD',
  'text': "#BREAKING: there was a deadly motorcycle car accident that happened to #Hagerstown today. I'll have more details at 5 @Your4State. #WHAG",
  'target': '1'},
 {'id': '141',
  'keyword': 'accident',
  'location': 'Gloucestershire , UK',
  'text': '@flowri were you marinading it or was it an accident?',
  'target': '0'},
 {'id': '143',
  'keyword': 'accident',
  'location': '',
  'text': "only had a car for not even a week and got in a fucking car accident .. Mfs can't fucking drive .",
  'target': '1'},
 {'id': '144',
  'keyword': 'accident',
  'location': 'UK',
  'text': '.@NorwayMFA #Bahrain police had previously died in a road accident they were not killed by explosion https://t.co/gFJfgTodad',
  'target': '1'},
 {'id': '145',
  'keyword': 'accident',
  'location': 'Nairobi, Kenya',
  'text': 'I still have not heard Church Leaders of Kenya coming forward to comment on the accident issue and disciplinary measures#ArrestPastorNganga',
  'target': '0'},
 {'id': '146',
  'keyword': 'aftershock',
  'location': 'Instagram - @heyimginog ',
  'text': '@afterShock_DeLo scuf ps live and the game... cya',
  'target': '0'},
 {'id': '149',
  'keyword': 'aftershock',
  'location': '304',
  'text': "'The man who can drive himself further once the effort gets painful is the man who will win.' \nRoger Bannister",
  'target': '0'},
 {'id': '151',
  'keyword': 'aftershock',
  'location': 'Switzerland',
  'text': '320 [IR] ICEMOON [AFTERSHOCK] | http://t.co/yNXnvVKCDA | @djicemoon | #Dubstep #TrapMusic #DnB #EDM #Dance #Ices\x89Û_ http://t.co/weQPesENku',
  'target': '0'},
 {'id': '153',
  'keyword': 'aftershock',
  'location': '304',
  'text': "'There is no victory at bargain basement prices.' Dwight David Eisenhower",
  'target': '0'},
 {'id': '156',
  'keyword': 'aftershock',
  'location': 'US',
  'text': '320 [IR] ICEMOON [AFTERSHOCK] | http://t.co/vAM5POdGyw | @djicemoon | #Dubstep #TrapMusic #DnB #EDM #Dance #Ices\x89Û_ http://t.co/zEVakJaPcz',
  'target': '0'},
 {'id': '157',
  'keyword': 'aftershock',
  'location': '304',
  'text': "'Nobody remembers who came in second.' Charles Schulz",
  'target': '0'},
 {'id': '158',
  'keyword': 'aftershock',
  'location': 'Instagram - @heyimginog ',
  'text': '@afterShock_DeLo im speaking from someone that is using a scuf on xb1 most of them people will end up getting on for ps also.',
  'target': '0'},
 {'id': '159',
  'keyword': 'aftershock',
  'location': '304',
  'text': "'The harder the conflict the more glorious the triumph.' Thomas Paine",
  'target': '0'},
 {'id': '160',
  'keyword': 'aftershock',
  'location': '',
  'text': "#GrowingUpSpoiled going clay pigeon shooting and crying because of the 'aftershock'",
  'target': '0'},
 {'id': '161',
  'keyword': 'aftershock',
  'location': 'Somewhere Only We Know ?',
  'text': 'So i guess no one actually wants any free Aftershock TC.....',
  'target': '0'},
 {'id': '162',
  'keyword': 'aftershock',
  'location': '',

In [13]:
file_data[2]

{'id': '5',
 'keyword': '',
 'location': '',
 'text': "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
 'target': '1'}

In [15]:
file_data[2]['text']

"All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"

In [16]:
# reading text files
relative_path = './data/cv042_10982.txt'

In [19]:
with open(relative_path,mode='r') as file:
    data = file.read()
print(data)

will hunting ( matt damon ) is a natural genius .
for a movie character , that's usually a death sentence .
it's a trait associated with what my brother calls " too good for this world " movies , like phenomenon or powder .
forgive me for spoiling the ending , but will doesn't die .
this is no formula movie .
in fact , it's quite fresh and original .
it's a character study more than anything , and that's not surprising , considering it was written by two actors : damon and co-star ben affleck .
will works whatever kind of job he can get .
first he's a janitor , then he works construction .
off-screen he speed reads books on any academic subject that interests him .
on-screen he hangs out with his friends , picking fights in robust , romanticized-hemingway fashion .
lambeau ( stellan skarsgard from breaking the waves ) , a math professor , learns that the janitor ( will ) is a genius with a special talent for advanced mathematics .
having confirmed he's not a fluke or a savant , he does what he can to get will into the education system .
he is firmly rejected .
finally , will lands in jail for one of his fights .
lambeau can get him probation instead of prison time as long as will agrees to therapy sessions and to discussing mathematics with him .
will ( barely ) decides to go for the therapy over prison .
lambeau treats will like a son .
he's proud of , and amazed by , will's accomplishments in mathematics .
he encourages will and tries to give him structure , knowing that , with a little discipline , he could be bigger than einstein .
will isn't really interested in academia .
he knows he would be the best in his field , and therefore spend all of his time in an office , explaining math to people like lambeau .
he would rather work construction , which breaks lambeau's heart .
meanwhile , will attends his mandated therapy sessions .
it's not long before he shreds all the therapists on lambeau's " a " list .
will has read enough psychology to know the tricks of the trade , and how to keep them from affecting him .
shrink after shrink refuses to return after will's mockery .
lambeau's last hope is his old college roommate , now a psychology teacher at a small-time community college .
knowing that will is going to try to shred him too , sean ( robin williams ) agrees to take him on as a favor to lambeau and for the chance to meet this next einstein .
true to form , will finds sean's emotional weakness and attacks .
but unlike the other shrinks , sean knows what he is in for and continues the sessions .
like a foster mother with a fussy child , sean knows that the attacks are defensive and is able to take them in stride .
like the foster mother , sean knows that time and quiet patience is the only approach .
robin williams is excellent in this role .
he's not an actor with a great range , but in the right roles he has great depth .
in this movie , as in awakenings , there comes a point when the quiet , shy man accomplishes something of great personal importance , and a smile of pure joy spreads up to his eyes .
williams is the only actor i can name who can make an audience cry just by smiling .
i have compared will to a foster child and that's not entirely fair .
emotionally , he has a lot to learn , but he is not a child .
he has thought about his life and made rational decisions about what he wants .
sean , his girlfriend , his pals , and lambeau all help him grow , but he didn't start out asking for , or particularly needing , help .
his exceptional gift singled him out , and those who love him kept pushing him in the right direction .
if i had to say anything bad about good will hunting is that it walks the line between drama and melodrama .
it's too sentimental and uplifiting for a straight drama , but the emotions are too subtle for melodrama .
it is emotionally engaging , but it's not quite larger than life .
this isn't a problem per se , but at times i didn't know quite how to take it .
but this is a relatively small complaint about a very good movie .
a good movie allows its characters to learn and grow .
it doesn't just happen ; it takes a good script , good acting , and good direction .
good will hunting has all three .
if you are at all inclined to see it , by all means , go .

In [20]:
file.close()

In [21]:
type(data)

str

In [22]:
from nltk.tokenize import word_tokenize
word_tokenize(data)

['will',
 'hunting',
 '(',
 'matt',
 'damon',
 ')',
 'is',
 'a',
 'natural',
 'genius',
 '.',
 'for',
 'a',
 'movie',
 'character',
 ',',
 'that',
 "'s",
 'usually',
 'a',
 'death',
 'sentence',
 '.',
 'it',
 "'s",
 'a',
 'trait',
 'associated',
 'with',
 'what',
 'my',
 'brother',
 'calls',
 '``',
 'too',
 'good',
 'for',
 'this',
 'world',
 '``',
 'movies',
 ',',
 'like',
 'phenomenon',
 'or',
 'powder',
 '.',
 'forgive',
 'me',
 'for',
 'spoiling',
 'the',
 'ending',
 ',',
 'but',
 'will',
 'does',
 "n't",
 'die',
 '.',
 'this',
 'is',
 'no',
 'formula',
 'movie',
 '.',
 'in',
 'fact',
 ',',
 'it',
 "'s",
 'quite',
 'fresh',
 'and',
 'original',
 '.',
 'it',
 "'s",
 'a',
 'character',
 'study',
 'more',
 'than',
 'anything',
 ',',
 'and',
 'that',
 "'s",
 'not',
 'surprising',
 ',',
 'considering',
 'it',
 'was',
 'written',
 'by',
 'two',
 'actors',
 ':',
 'damon',
 'and',
 'co-star',
 'ben',
 'affleck',
 '.',
 'will',
 'works',
 'whatever',
 'kind',
 'of',
 'job',
 'he',
 'can',
 'get',
 '.',
 'first',
 'he',
 "'s",
 'a',
 'janitor',
 ',',
 'then',
 'he',
 'works',
 'construction',
 '.',
 'off-screen',
 'he',
 'speed',
 'reads',
 'books',
 'on',
 'any',
 'academic',
 'subject',
 'that',
 'interests',
 'him',
 '.',
 'on-screen',
 'he',
 'hangs',
 'out',
 'with',
 'his',
 'friends',
 ',',
 'picking',
 'fights',
 'in',
 'robust',
 ',',
 'romanticized-hemingway',
 'fashion',
 '.',
 'lambeau',
 '(',
 'stellan',
 'skarsgard',
 'from',
 'breaking',
 'the',
 'waves',
 ')',
 ',',
 'a',
 'math',
 'professor',
 ',',
 'learns',
 'that',
 'the',
 'janitor',
 '(',
 'will',
 ')',
 'is',
 'a',
 'genius',
 'with',
 'a',
 'special',
 'talent',
 'for',
 'advanced',
 'mathematics',
 '.',
 'having',
 'confirmed',
 'he',
 "'s",
 'not',
 'a',
 'fluke',
 'or',
 'a',
 'savant',
 ',',
 'he',
 'does',
 'what',
 'he',
 'can',
 'to',
 'get',
 'will',
 'into',
 'the',
 'education',
 'system',
 '.',
 'he',
 'is',
 'firmly',
 'rejected',
 '.',
 'finally',
 ',',
 'will',
 'lands',
 'in',
 'jail',
 'for',
 'one',
 'of',
 'his',
 'fights',
 '.',
 'lambeau',
 'can',
 'get',
 'him',
 'probation',
 'instead',
 'of',
 'prison',
 'time',
 'as',
 'long',
 'as',
 'will',
 'agrees',
 'to',
 'therapy',
 'sessions',
 'and',
 'to',
 'discussing',
 'mathematics',
 'with',
 'him',
 '.',
 'will',
 '(',
 'barely',
 ')',
 'decides',
 'to',
 'go',
 'for',
 'the',
 'therapy',
 'over',
 'prison',
 '.',
 'lambeau',
 'treats',
 'will',
 'like',
 'a',
 'son',
 '.',
 'he',
 "'s",
 'proud',
 'of',
 ',',
 'and',
 'amazed',
 'by',
 ',',
 'will',
 "'s",
 'accomplishments',
 'in',
 'mathematics',
 '.',
 'he',
 'encourages',
 'will',
 'and',
 'tries',
 'to',
 'give',
 'him',
 'structure',
 ',',
 'knowing',
 'that',
 ',',
 'with',
 'a',
 'little',
 'discipline',
 ',',
 'he',
 'could',
 'be',
 'bigger',
 'than',
 'einstein',
 '.',
 'will',
 'is',
 "n't",
 'really',
 'interested',
 'in',
 'academia',
 '.',
 'he',
 'knows',
 'he',
 'would',
 'be',
 'the',
 'best',
 'in',
 'his',
 'field',
 ',',
 'and',
 'therefore',
 'spend',
 'all',
 'of',
 'his',
 'time',
 'in',
 'an',
 'office',
 ',',
 'explaining',
 'math',
 'to',
 'people',
 'like',
 'lambeau',
 '.',
 'he',
 'would',
 'rather',
 'work',
 'construction',
 ',',
 'which',
 'breaks',
 'lambeau',
 "'s",
 'heart',
 '.',
 'meanwhile',
 ',',
 'will',
 'attends',
 'his',
 'mandated',
 'therapy',
 'sessions',
 '.',
 'it',
 "'s",
 'not',
 'long',
 'before',
 'he',
 'shreds',
 'all',
 'the',
 'therapists',
 'on',
 'lambeau',
 "'s",
 '``',
 'a',
 '``',
 'list',
 '.',
 'will',
 'has',
 'read',
 'enough',
 'psychology',
 'to',
 'know',
 'the',
 'tricks',
 'of',
 'the',
 'trade',
 ',',
 'and',
 'how',
 'to',
 'keep',
 'them',
 'from',
 'affecting',
 'him',
 '.',
 'shrink',
 'after',
 'shrink',
 'refuses',
 'to',
 'return',
 'after',
 'will',
 "'s",
 'mockery',
 '.',
 'lambeau',
 "'s",
 'last',
 'hope',
 'is',
 'his',
 'old',
 'college',
 'roommate',
 ',',
 'now',
 'a',
 'psychology',
 'teacher',
 'at',
 'a',
 'small-time',
 'community',
 'college',
 '.',
 'knowing',
 'that',
 'will',
 'is',
 'going',
 'to',
 'try',
 'to',
 'shred',
 'him',
 'too',
 ',',
 'sean',
 '(',
 'robin',
 'williams',
 ')',
 'agrees',
 'to',
 'take',
 'him',
 'on',
 'as',
 'a',
 'favor',
 'to',
 'lambeau',
 'and',
 'for',
 'the',
 'chance',
 'to',
 'meet',
 'this',
 'next',
 'einstein',
 '.',
 'true',
 'to',
 'form',
 ',',
 'will',
 'finds',
 'sean',
 "'s",
 'emotional',
 'weakness',
 'and',
 'attacks',
 '.',
 'but',
 'unlike',
 'the',
 'other',
 'shrinks',
 ',',
 'sean',
 'knows',
 'what',
 'he',
 'is',
 'in',
 'for',
 'and',
 'continues',
 'the',
 'sessions',
 '.',
 'like',
 'a',
 'foster',
 'mother',
 'with',
 'a',
 'fussy',
 'child',
 ',',
 'sean',
 'knows',
 'that',
 'the',
 'attacks',
 'are',
 'defensive',
 'and',
 'is',
 'able',
 'to',
 'take',
 'them',
 'in',
 'stride',
 '.',
 'like',
 'the',
 'foster',
 'mother',
 ',',
 'sean',
 'knows',
 'that',
 'time',
 'and',
 'quiet',
 'patience',
 'is',
 'the',
 'only',
 'approach',
 '.',
 'robin',
 'williams',
 'is',
 'excellent',
 'in',
 'this',
 'role',
 '.',
 'he',
 "'s",
 'not',
 'an',
 'actor',
 'with',
 'a',
 'great',
 'range',
 ',',
 'but',
 'in',
 'the',
 'right',
 'roles',
 'he',
 'has',
 'great',
 'depth',
 '.',
 'in',
 'this',
 'movie',
 ',',
 'as',
 'in',
 'awakenings',
 ',',
 'there',
 'comes',
 'a',
 'point',
 'when',
 'the',
 'quiet',
 ',',
 'shy',
 'man',
 'accomplishes',
 'something',
 'of',
 'great',
 'personal',
 'importance',
 ',',
 'and',
 'a',
 'smile',
 'of',
 'pure',
 'joy',
 'spreads',
 'up',
 'to',
 'his',
 'eyes',
 '.',
 'williams',
 'is',
 'the',
 'only',
 'actor',
 'i',
 'can',
 'name',
 'who',
 'can',
 'make',
 'an',
 'audience',
 'cry',
 'just',
 'by',
 'smiling',
 '.',
 'i',
 'have',
 'compared',
 'will',
 'to',
 'a',
 'foster',
 'child',
 'and',
 'that',
 "'s",
 'not',
 'entirely',
 'fair',
 '.',
 'emotionally',
 ',',
 'he',
 'has',
 'a',
 'lot',
 'to',
 'learn',
 ',',
 'but',
 'he',
 'is',
 'not',
 'a',
 'child',
 '.',
 'he',
 'has',
 'thought',
 'about',
 'his',
 'life',
 'and',
 'made',
 'rational',
 'decisions',
 'about',
 'what',
 'he',
 'wants',
 '.',
 'sean',
 ',',
 'his',
 'girlfriend',
 ',',
 'his',
 'pals',
 ',',
 'and',
 'lambeau',
 'all',
 'help',
 'him',
 'grow',
 ',',
 'but',
 'he',
 'did',
 "n't",
 'start',
 'out',
 'asking',
 'for',
 ',',
 'or',
 'particularly',
 'needing',
 ',',
 'help',
 '.',
 'his',
 'exceptional',
 'gift',
 'singled',
 'him',
 'out',
 ',',
 'and',
 'those',
 'who',
 'love',
 'him',
 'kept',
 'pushing',
 'him',
 'in',
 'the',
 'right',
 'direction',
 '.',
 'if',
 'i',
 'had',
 'to',
 'say',
 'anything',
 'bad',
 'about',
 'good',
 'will',
 'hunting',
 'is',
 'that',
 'it',
 'walks',
 'the',
 'line',
 'between',
 'drama',
 'and',
 'melodrama',
 '.',
 'it',
 "'s",
 'too',
 'sentimental',
 'and',
 'uplifiting',
 'for',
 'a',
 'straight',
 'drama',
 ',',
 'but',
 'the',
 'emotions',
 'are',
 'too',
 'subtle',
 'for',
 'melodrama',
 '.',
 'it',
 'is',
 'emotionally',
 'engaging',
 ',',
 'but',
 'it',
 "'s",
 'not',
 'quite',
 'larger',
 'than',
 'life',
 '.',
 'this',
 'is',
 "n't",
 'a',
 'problem',
 'per',
 'se',
 ',',
 'but',
 'at',
 'times',
 'i',
 'did',
 "n't",
 'know',
 'quite',
 'how',
 'to',
 'take',
 'it',
 '.',
 'but',
 'this',
 'is',
 'a',
 'relatively',
 'small',
 'complaint',
 'about',
 'a',
 'very',
 'good',
 'movie',
 '.',
 'a',
 'good',
 'movie',
 'allows',
 'its',
 'characters',
 'to',
 'learn',
 'and',
 'grow',
 '.',
 'it',
 'does',
 "n't",
 'just',
 'happen',
 ';',
 'it',
 'takes',
 'a',
 'good',
 'script',
 ',',
 'good',
 'acting',
 ',',
 'and',
 'good',
 'direction',
 '.',
 'good',
 'will',
 'hunting',
 'has',
 'all',
 'three',
 '.',
 'if',
 'you',
 'are',
 'at',
 'all',
 'inclined',
 'to',
 'see',
 'it',
 ',',
 'by',
 'all',
 'means',
 ',',
 'go',
 '.']

In [24]:
import nltk

In [25]:
nltk.FreqDist(word_tokenize(data))

FreqDist({'.': 51, ',': 50, 'a': 31, 'he': 24, 'to': 23, 'and': 22, 'the': 21, 'will': 20, "'s": 19, 'is': 17, ...})

I have a folder name data next to this notebook - this is where our file is located:

In [5]:
!ls data

cv042_10982.txt tweets_data.csv

Inside this folder, we have a *tweets_data.csv file*, let's load it using pandas and using python base:

Using pandas is really simple:

In [8]:
# We can just provide a path to the read_csv function - the
# returning element is a pandas dataframe
pd.read_csv('./data/tweets_data.csv', sep=',')

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [5]:
with open('./data/tweets_data.csv', mode='r') as csv_file:
    csv_f = csv.DictReader(csv_file)  
    file_data = []
    for row in csv_f:
        file_data.append(dict(row))

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2245: character maps to <undefined>

Encodings can sometime give us some trouble:

In [6]:
with open('./data/tweets_data.csv', mode='r', encoding="utf-8") as csv_file:
    csv_f = csv.DictReader(csv_file)  
    file_data = []
    for row in csv_f:
        file_data.append(dict(row))

In [7]:
file_data[2]

{'id': '5',
 'keyword': '',
 'location': '',
 'text': "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
 'target': '1'}

If we would want to read the text from this dictionary:

In [8]:
file_data[2]['text']

"All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"

### 1.2 - Reading TXT Files

To read txt files into Python we can also use the same logic:
    - Read using the Pandas Library;
    - Read using base Python;

In [9]:
# Reading some text files using Pandas (if it is not a comma separated
# text) may get weird:
pd.read_csv('./data/cv042_10982.txt', sep = '\t')

   will hunting ( matt damon ) is a natural genius .
0   for a movie character , that's usually a death...
1   it's a trait associated with what my brother c...
2   forgive me for spoiling the ending , but will ...
3                         this is no formula movie .
4          in fact , it's quite fresh and original .
5   it's a character study more than anything , an...
6       will works whatever kind of job he can get .
7   first he's a janitor , then he works construct...
8   off-screen he speed reads books on any academi...
9   on-screen he hangs out with his friends , pick...
10  lambeau ( stellan skarsgard from breaking the ...
11  having confirmed he's not a fluke or a savant ...
12                           he is firmly rejected .
13  finally , will lands in jail for one of his fi...
14  lambeau can get him probation instead of priso...
15  will ( barely ) decides to go for the therapy ...
16                  lambeau treats will like a son .
17  he's proud of , and amazed by , will's accompl...
18  he encourages will and tries to give him struc...
19        will isn't really interested in academia .
20  he knows he would be the best in his field , a...
21  he would rather work construction , which brea...
22  meanwhile , will attends his mandated therapy ...
23  it's not long before he shreds all the therapi...
24  will has read enough psychology to know the tr...
25  shrink after shrink refuses to return after wi...
26  lambeau's last hope is his old college roommat...
27  knowing that will is going to try to shred him...
28  true to form , will finds sean's emotional wea...
29  but unlike the other shrinks , sean knows what...
30  like a foster mother with a fussy child , sean...
31  like the foster mother , sean knows that time ...
32        robin williams is excellent in this role .
33  he's not an actor with a great range , but in ...
34  in this movie , as in awakenings , there comes...
35  williams is the only actor i can name who can ...
36  i have compared will to a foster child and tha...
37  emotionally , he has a lot to learn , but he i...
38  he has thought about his life and made rationa...
39  sean , his girlfriend , his pals , and lambeau...
40  his exceptional gift singled him out , and tho...
41  if i had to say anything bad about good will h...
42  it's too sentimental and uplifiting for a stra...
43  it is emotionally engaging , but it's not quit...
44  this isn't a problem per se , but at times i d...
45  but this is a relatively small complaint about...
46  a good movie allows its characters to learn an...
47  it doesn't just happen ; it takes a good scrip...
48                 good will hunting has all three .
49  if you are at all inclined to see it , by all ...

In [10]:
f = open("./data/cv042_10982.txt", "r")
print(f.read())
# After using read you can't assign the text
# to a value
text = f.read()
f.close()

will hunting ( matt damon ) is a natural genius .
for a movie character , that's usually a death sentence .
it's a trait associated with what my brother calls " too good for this world " movies , like phenomenon or powder .
forgive me for spoiling the ending , but will doesn't die .
this is no formula movie .
in fact , it's quite fresh and original .
it's a character study more than anything , and that's not surprising , considering it was written by two actors : damon and co-star ben affleck .
will works whatever kind of job he can get .
first he's a janitor , then he works construction .
off-screen he speed reads books on any academic subject that interests him .
on-screen he hangs out with his friends , picking fights in robust , romanticized-hemingway fashion .
lambeau ( stellan skarsgard from breaking the waves ) , a math professor , learns that the janitor ( will ) is a genius with a special talent for advanced mathematics .
having confirmed he's not a fluke or a savant , he does what he can to get will into the education system .
he is firmly rejected .
finally , will lands in jail for one of his fights .
lambeau can get him probation instead of prison time as long as will agrees to therapy sessions and to discussing mathematics with him .
will ( barely ) decides to go for the therapy over prison .
lambeau treats will like a son .
he's proud of , and amazed by , will's accomplishments in mathematics .
he encourages will and tries to give him structure , knowing that , with a little discipline , he could be bigger than einstein .
will isn't really interested in academia .
he knows he would be the best in his field , and therefore spend all of his time in an office , explaining math to people like lambeau .
he would rather work construction , which breaks lambeau's heart .
meanwhile , will attends his mandated therapy sessions .
it's not long before he shreds all the therapists on lambeau's " a " list .
will has read enough psychology to know the tricks of the trade , and how to keep them from affecting him .
shrink after shrink refuses to return after will's mockery .
lambeau's last hope is his old college roommate , now a psychology teacher at a small-time community college .
knowing that will is going to try to shred him too , sean ( robin williams ) agrees to take him on as a favor to lambeau and for the chance to meet this next einstein .
true to form , will finds sean's emotional weakness and attacks .
but unlike the other shrinks , sean knows what he is in for and continues the sessions .
like a foster mother with a fussy child , sean knows that the attacks are defensive and is able to take them in stride .
like the foster mother , sean knows that time and quiet patience is the only approach .
robin williams is excellent in this role .
he's not an actor with a great range , but in the right roles he has great depth .
in this movie , as in awakenings , there comes a point when the quiet , shy man accomplishes something of great personal importance , and a smile of pure joy spreads up to his eyes .
williams is the only actor i can name who can make an audience cry just by smiling .
i have compared will to a foster child and that's not entirely fair .
emotionally , he has a lot to learn , but he is not a child .
he has thought about his life and made rational decisions about what he wants .
sean , his girlfriend , his pals , and lambeau all help him grow , but he didn't start out asking for , or particularly needing , help .
his exceptional gift singled him out , and those who love him kept pushing him in the right direction .
if i had to say anything bad about good will hunting is that it walks the line between drama and melodrama .
it's too sentimental and uplifiting for a straight drama , but the emotions are too subtle for melodrama .
it is emotionally engaging , but it's not quite larger than life .
this isn't a problem per se , but at times i didn't know quite how to take it .
but this is a relatively small complaint about a very good movie .
a good movie allows its characters to learn and grow .
it doesn't just happen ; it takes a good script , good acting , and good direction .
good will hunting has all three .
if you are at all inclined to see it , by all means , go .

In [11]:
f = open("./data/cv042_10982.txt", "r")
movie_review = f.read()

In [12]:
print(movie_review)

will hunting ( matt damon ) is a natural genius .
for a movie character , that's usually a death sentence .
it's a trait associated with what my brother calls " too good for this world " movies , like phenomenon or powder .
forgive me for spoiling the ending , but will doesn't die .
this is no formula movie .
in fact , it's quite fresh and original .
it's a character study more than anything , and that's not surprising , considering it was written by two actors : damon and co-star ben affleck .
will works whatever kind of job he can get .
first he's a janitor , then he works construction .
off-screen he speed reads books on any academic subject that interests him .
on-screen he hangs out with his friends , picking fights in robust , romanticized-hemingway fashion .
lambeau ( stellan skarsgard from breaking the waves ) , a math professor , learns that the janitor ( will ) is a genius with a special talent for advanced mathematics .
having confirmed he's not a fluke or a savant , he does what he can to get will into the education system .
he is firmly rejected .
finally , will lands in jail for one of his fights .
lambeau can get him probation instead of prison time as long as will agrees to therapy sessions and to discussing mathematics with him .
will ( barely ) decides to go for the therapy over prison .
lambeau treats will like a son .
he's proud of , and amazed by , will's accomplishments in mathematics .
he encourages will and tries to give him structure , knowing that , with a little discipline , he could be bigger than einstein .
will isn't really interested in academia .
he knows he would be the best in his field , and therefore spend all of his time in an office , explaining math to people like lambeau .
he would rather work construction , which breaks lambeau's heart .
meanwhile , will attends his mandated therapy sessions .
it's not long before he shreds all the therapists on lambeau's " a " list .
will has read enough psychology to know the tricks of the trade , and how to keep them from affecting him .
shrink after shrink refuses to return after will's mockery .
lambeau's last hope is his old college roommate , now a psychology teacher at a small-time community college .
knowing that will is going to try to shred him too , sean ( robin williams ) agrees to take him on as a favor to lambeau and for the chance to meet this next einstein .
true to form , will finds sean's emotional weakness and attacks .
but unlike the other shrinks , sean knows what he is in for and continues the sessions .
like a foster mother with a fussy child , sean knows that the attacks are defensive and is able to take them in stride .
like the foster mother , sean knows that time and quiet patience is the only approach .
robin williams is excellent in this role .
he's not an actor with a great range , but in the right roles he has great depth .
in this movie , as in awakenings , there comes a point when the quiet , shy man accomplishes something of great personal importance , and a smile of pure joy spreads up to his eyes .
williams is the only actor i can name who can make an audience cry just by smiling .
i have compared will to a foster child and that's not entirely fair .
emotionally , he has a lot to learn , but he is not a child .
he has thought about his life and made rational decisions about what he wants .
sean , his girlfriend , his pals , and lambeau all help him grow , but he didn't start out asking for , or particularly needing , help .
his exceptional gift singled him out , and those who love him kept pushing him in the right direction .
if i had to say anything bad about good will hunting is that it walks the line between drama and melodrama .
it's too sentimental and uplifiting for a straight drama , but the emotions are too subtle for melodrama .
it is emotionally engaging , but it's not quite larger than life .
this isn't a problem per se , but at times i didn't know quite how to take it .
but this is a relatively small complaint about a very good movie .
a good movie allows its characters to learn and grow .
it doesn't just happen ; it takes a good script , good acting , and good direction .
good will hunting has all three .
if you are at all inclined to see it , by all means , go .

We can now work this text as any other text that we have worked with, let's confirm it with the type of the object:

In [13]:
type(movie_review)

str