## Linear Regression implementation

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model

### simple linear regression model (one predictor only)

In [2]:
# Load the data into a pandas dataframe
iris = sns.load_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X = iris[["petal_length"]] #predictor
y = iris["petal_width"] #response

In [4]:
#Linear regression
# Note the swap of X and y
model = sm.OLS(y, X)
results = model.fit()
# Statsmodels gives R-like statistical output
print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:            petal_width   R-squared (uncentered):                   0.967
Model:                            OLS   Adj. R-squared (uncentered):              0.967
Method:                 Least Squares   F-statistic:                              4417.
Date:                Mon, 28 Sep 2026   Prob (F-statistic):                   1.22e-112
Time:                        10:03:00   Log-Likelihood:                         -8.7179
No. Observations:                 150   AIC:                                      19.44
Df Residuals:                     149   BIC:                                      22.45
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
petal_length     0.3365      0.005     66.463      0.000       0.327       0.347
==============================================================================
Omnibus:                       19.720   Durbin-Watson:                   0.857
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.498
Skew:                           0.957   Prob(JB):                     7.90e-06
Kurtosis:                       3.311   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
#where is the intercept info?

In [6]:
X = iris["petal_length"]
X = np.vander(X, 2) # add a constant row for the intercept
y = iris["petal_width"]

model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            petal_width   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     1882.
Date:                Mon, 28 Sep 2026   Prob (F-statistic):           4.68e-86
Time:                        10:03:44   Log-Likelihood:                 24.796
No. Observations:                 150   AIC:                            -45.59
Df Residuals:                     148   BIC:                            -39.57
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4158      0.010     43.387      0.000       0.397       0.435
const         -0.3631      0.040     -9.131      0.000      -0.442      -0.285
==============================================================================
Omnibus:                        5.765   Durbin-Watson:                   1.455
Prob(Omnibus):                  0.056   Jarque-Bera (JB):                5.555
Skew:                           0.359   Prob(JB):                       0.0622
Kurtosis:                       3.611   Cond. No.                         10.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### Petal_width=0.41-0.36* (petal_length)

### multiple linear regression- more than one predictor

In [7]:
X = iris[["petal_length","sepal_length"]] #predictors
y = iris["petal_width"]

In [8]:
#Multiple Linear regression
# Note the swap of X and y
X = iris[["petal_length","sepal_length"]]
X = sm.add_constant(X) # another way to add a constant row for an intercept
y = iris["petal_width"]

model = sm.OLS(y, X)
results = model.fit()
print(results.summary())
model = sm.OLS(y, X)
results = model.fit()
# Statsmodels gives R-like statistical output
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            petal_width   R-squared:                       0.929
Model:                            OLS   Adj. R-squared:                  0.928
Method:                 Least Squares   F-statistic:                     962.1
Date:                Mon, 28 Sep 2026   Prob (F-statistic):           3.60e-85
Time:                        10:03:58   Log-Likelihood:                 26.792
No. Observations:                 150   AIC:                            -47.58
Df Residuals:                     147   BIC:                            -38.55
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0090      0.182     -0.049      0.961      -0.369       0.351
petal_length     0.4494      0.019     23.205      0.000       0.411       0.488
sepal_length    -0.0822      0.041     -1.992      0.048      -0.164      -0.001
==============================================================================
Omnibus:                        6.657   Durbin-Watson:                   1.414
Prob(Omnibus):                  0.036   Jarque-Bera (JB):                6.663
Skew:                           0.386   Prob(JB):                       0.0357
Kurtosis:                       3.685   Cond. No.                         80.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            petal_width   R-squared:                       0.929
Model:                            OLS   Adj. R-squared:                  0.928
Method:                 Least Squares   F-statistic:                     962.1
Date:                Mon, 28 Sep 2026   Prob (F-statistic):           3.60e-85
Time:                        10:03:58   Log-Likelihood:                 26.792
No. Observations:                 150   AIC:                            -47.58
Df Residuals:                     147   BIC:                            -38.55
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0090      0.182     -0.049      0.961      -0.369       0.351
petal_length     0.4494      0.019     23.205      0.000       0.411       0.488
sepal_length    -0.0822      0.041     -1.992      0.048      -0.164      -0.001
==============================================================================
Omnibus:                        6.657   Durbin-Watson:                   1.414
Prob(Omnibus):                  0.036   Jarque-Bera (JB):                6.663
Skew:                           0.386   Prob(JB):                       0.0357
Kurtosis:                       3.685   Cond. No.                         80.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### use categorical variables

In [9]:
dummies = pd.get_dummies(iris["species"])
# Add to the original dataframe
iris = pd.concat([iris, dummies], axis=1)#assign numerical values to the different species
iris.head()

,sepal_length,sepal_width,petal_length,petal_width,species,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,setosa,True,False,False
1,4.9,3.0,1.4,0.2,setosa,True,False,False
2,4.7,3.2,1.3,0.2,setosa,True,False,False
3,4.6,3.1,1.5,0.2,setosa,True,False,False
4,5.0,3.6,1.4,0.2,setosa,True,False,False

In [10]:
X = iris[["petal_length","sepal_length", "setosa", "versicolor", "virginica"]]
X = sm.add_constant(X) # another way to add a constant row for an intercept
y = iris["petal_width"]

model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            petal_width   R-squared:                       0.946
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     629.8
Date:                Mon, 28 Sep 2026   Prob (F-statistic):           1.54e-90
Time:                        10:04:15   Log-Likelihood:                 46.705
No. Observations:                 150   AIC:                            -83.41
Df Residuals:                     145   BIC:                            -68.36
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.2533      0.127      1.993      0.048       0.002       0.504
petal_length     0.2319      0.053      4.393      0.000       0.128       0.336
sepal_length    -0.0017      0.044     -0.038      0.969      -0.089       0.086
setosa          -0.3378      0.097     -3.501      0.001      -0.529      -0.147
versicolor       0.0948      0.055      1.717      0.088      -0.014       0.204
virginica        0.4963      0.097      5.090      0.000       0.304       0.689
==============================================================================
Omnibus:                        6.224   Durbin-Watson:                   1.736
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                9.603
Skew:                          -0.112   Prob(JB):                      0.00822
Kurtosis:                       4.219   Cond. No.                     1.53e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.35e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/var/folders/8t/4ttt_tc53hs994xcrmjg2p880000gn/T/ipykernel_48463/2951811809.py:6: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  results = model.fit()

In [11]:
# you would be inclined to choose the model that had the lower AIC or BIC value

In [13]:
# Fit the linear model using sklearn
#from sklearn import linear_model
model = linear_model.LinearRegression()
results = model.fit(X, y)

# Print the coefficients
print(results.intercept_, results.coef_)

0.3376683161818005 [ 0.          0.23192122 -0.00169337 -0.42226013  0.01039913  0.411861  ]